'use strict';

const fs = require('fs');
const path = require('path');
const app = require('electron').app;

const fatal = function(err)
{
  console.log(err);
  app.exit(1);
}

const version = app.getVersion();
const electonGypScript = path.normalize(path.join(__dirname, '..', 'backend', 'electron-gyp.sh'));

const buildScript =
`#!/bin/bash
# THIS SCRIPT IS AUTOGENERATED!
# Update by running the following in the parent directory:
#    ./node_modules/.bin/electron scripts/update-version.js in parent

exec node-gyp $1 --target=${version} --arch=x64 --dist-url=https://atom.io/download/atom-shell \${@:2}`;

try {
  fs.writeFileSync(electonGypScript, buildScript, {mode: 0o775});
  console.log("Updated '" + electonGypScript + "' with electron version: " + version);

} catch (err) {
  fatal(err);

} finally {
  app.exit(0);
}
